# generated by datamodel-codegen:
#   filename:  VM.json
#   timestamp: 2023-04-25T03:55:36+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class VM(BaseModel):
    svrSledNo: Optional[str] = None
    svrMACAddress: Optional[str] = None
    svrRobinVer: Optional[str] = None
    svrFPGAVer: Optional[str] = None
    svrKernelVer: Optional[str] = None
    svrEMSId: Optional[str] = None
    svrClusterRole: Optional[str] = None
    svrChassisNo: Optional[str] = None
    svrBMCVer: Optional[str] = None
    svrBMCHost: Optional[str] = None
    svrRAIDVer: Optional[str] = None
    svrNICVer: Optional[str] = None
    svrSSDVer: Optional[str] = None
    svrPhysicalHostName: Optional[str] = None
    svrOSName: Optional[str] = None
    svrNodeElementId: Optional[str] = None
    svrClusterPodId: Optional[str] = None
    svrNootTime: Optional[str] = None
    srvCPUTotal: Optional[str] = None
    svrCPUUsed: Optional[str] = None
    svrMemTotalMb: Optional[str] = None
    svrMemUsedMb: Optional[str] = None
    svrStorageTotalGb: Optional[str] = None
    svrStorageUsedGb: Optional[str] = None
    svrSKUType: Optional[str] = None
    svrFlavorOS: Optional[str] = None
    svrFlavorVDU: Optional[str] = None
    svrFlavorSRIOV: Optional[str] = None
    svrFlavorVCU: Optional[str] = None
    svrFlavorFWUP: Optional[str] = None
    svrFlavorNICDdriver: Optional[str] = None
    svrRcpVer: Optional[str] = None
    svrRcpRev: Optional[str] = None
    svrRcpWorkload: Optional[str] = None
    svrDomain: Optional[str] = None
    svrDNS: Optional[str] = None
    svrNTP: Optional[str] = None
    svrGateWay: Optional[str] = None
    svrFlavorNICDippDriver: Optional[str] = None
    meHostname: Optional[str] = None
    mePhysicalhostName: Optional[str] = None
    meNeId: Optional[str] = None
    meFMEMSId: Optional[str] = None
    mePMEMSId: Optional[str] = None
    meCMEMDId: Optional[str] = None
    meSubType: Optional[str] = None
    meSwVersion: Optional[str] = None
    meBuildVersion: Optional[str] = None
    meLicense: Optional[str] = None
    meState: Optional[str] = None
    meEMSstatus: Optional[str] = None
    meMgmtIPV4: Optional[str] = None
    meMgmtIPV6: Optional[str] = None
    meFQDN: Optional[str] = None
    meStage: Optional[str] = None
    meSecured: Optional[str] = None
    meOnAirDate: Optional[str] = None
    meTechnology: Optional[str] = None
    meRole: Optional[str] = None
    id: Optional[str] = None
    href: Optional[str] = None
    name: Optional[str] = None
    displayName: Optional[str] = None
    gId: Optional[str] = None
    uuid: Optional[str] = None
    originid: Optional[str] = None
    type: Optional[str] = None
    baseType: Optional[str] = None
    description: Optional[str] = None
    typeversion: Optional[str] = None
    status: Optional[str] = None
    operatationalState: Optional[str] = None
    administrativeState: Optional[str] = None
    source: Optional[str] = None
    creationTime: Optional[str] = None
    creatorid: Optional[str] = None
    modificationTime: Optional[str] = None
    modifierid: Optional[str] = None
    category: Optional[str] = None
    vendor: Optional[str] = None
    domain: Optional[str] = None
    specificationId: Optional[str] = None
    isDeleted: Optional[str] = None
    isEntity: Optional[str] = None
    metaParam: Optional[str] = None

    class Config:
        allow_population_by_field_name = True
        from pydantic import Extra
        extra = Extra.forbid