# generated by datamodel-codegen:
#   filename:  VNF.json
#   timestamp: 2023-04-24T11:37:16+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class VNF(BaseModel):
    meHostname: Optional[str] = None
    mePhysicalhostName: Optional[str] = None
    meNeId: Optional[str] = None
    meFMEMSId: Optional[str] = None
    mePMEMSId: Optional[str] = None
    meCMEMDId: Optional[str] = None
    meSubType: Optional[str] = None
    meSwVersion: Optional[str] = None
    meBuildVersion: Optional[str] = None
    meLicense: Optional[str] = None
    meState: Optional[str] = None
    meEMSstatus: Optional[str] = None
    meMgmtIPV4: Optional[str] = None
    meMgmtIPV6: Optional[str] = None
    meFQDN: Optional[str] = None
    meStage: Optional[str] = None
    meSecured: Optional[str] = None
    meOnAirDate: Optional[str] = None
    meTechnology: Optional[str] = None
    meRole: Optional[str] = None
    id: Optional[str] = None
    href: Optional[str] = None
    name: Optional[str] = None
    displayName: Optional[str] = None
    gId: Optional[str] = None
    uuid: Optional[str] = None
    originid: Optional[str] = None
    type: Optional[str] = None
    baseType: Optional[str] = None
    description: Optional[str] = None
    typeversion: Optional[str] = None
    status: Optional[str] = None
    operatationalState: Optional[str] = None
    administrativeState: Optional[str] = None
    source: Optional[str] = None
    creationTime: Optional[str] = None
    creatorid: Optional[str] = None
    modificationTime: Optional[str] = None
    modifierid: Optional[str] = None
    category: Optional[str] = None
    vendor: Optional[str] = None
    domain: Optional[str] = None
    specificationId: Optional[str] = None
    isDeleted: Optional[str] = None
    isEntity: Optional[str] = None
    metaParam: Optional[str] = None
    vnfLicense: Optional[str] = None
    vnfInstantiationlevel: Optional[str] = None
    vnfUsername: Optional[str] = None
    vnfChecksum: Optional[str] = None
    vnfManagedbyvnfm: Optional[str] = None
    vnfSwversionstatus: Optional[str] = None
    vnfRPoolName: Optional[str] = None
    vnfIPPoolName: Optional[str] = None
    vnfStatus: Optional[str] = None
    vnfType: Optional[str] = None

    class Config:
        from pydantic import Extra
        extra = Extra.forbid